name: deploy
on: {push: {branches: [source]}}
defaults:
  run:
    working-directory: repo
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with: { path: repo } 
    - uses: haskell-actions/setup@v2.4.7
    - name: install
      run: |
        stack install hakyll
    - name: build
      run: |
        stack build
        stack exec site build

    - name: deploy
      run: |
        cd site_
        git init -b gh-pages
        git config user.name 'GitHub Actions'
        git config user.email 'zrallwein@gmail.com'
        git add .
        git commit -m 'Deploy to GitHub Pages'
        git push --force 'https://axenna:${{ github.token }}@github.com/${{ github.repository }}' gh-pages

